INSERT INTO Categories (Category, Description) VALUES ('Beauty', 'Products designed to enhance or improve a persons appearance');
INSERT INTO Categories (Category, Description) VALUES ('Women', 'Marketed towards women; Skincare, Makeup, Haircare, Fragrances, Personal Hygiene Products, Clothing');
INSERT INTO Categories (Category, Description) VALUES ('Home', 'Products designed to be used in and around the home to improve comfort, functionality and aesthetics');
INSERT INTO Categories (Category, Description) VALUES ('Electronics', 'Devices and equipment that use electronic circuits, microprocessors and other digital technonologies to perform specific functions');
INSERT INTO Categories (Category, Description) VALUES ('Men', 'Marketed towards men; Grooming, Skincare, Fragrances, Clothing, Health and Wellness');
INSERT INTO Categories (Category, Description) VALUES ('Vintage & Collectibles', 'Items that are old or rave and have a certain level of historical or cultural significance');
INSERT INTO Categories (Category, Description) VALUES ('Kids', 'Marketed towards children; Toys, Clothing, School supplies, Baby gear, Art supplies');
INSERT INTO Categories (Category, Description) VALUES ('Others', 'Others');
INSERT INTO Categories (Category, Description) VALUES ('Handmade', 'Items made by hand rather than being mass-produced like machines');
INSERT INTO Categories (Category, Description) VALUES ('Sports & Outdoors', 'Products designed for people who enjoy participating in outdoor activities or sports');
