CREATE TABLE IF NOT EXISTS Users (
	Email VARCHAR(256) NOT NULL,
	Username CHAR(14) UNIQUE NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Join_date DATE NOT NULL,
	PRIMARY KEY(Email)
);

CREATE TABLE IF NOT EXISTS Seller (
	Seller VARCHAR(256) NOT NULL REFERENCES Users(Email) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Username VARCHAR(16) NOT NULL,
	Number VARCHAR(20) NOT NULL,
	PRIMARY KEY (Seller),
	FOREIGN KEY (Username) REFERENCES Users(Username) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS Buyer (
	Buyer VARCHAR(256) REFERENCES Users(Email) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Username VARCHAR(16),
	Number VARCHAR(20) NOT NULL,
	PRIMARY KEY(Buyer),
	FOREIGN KEY (Username) REFERENCES Users(Username) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS Listings (
	Name VARCHAR(256) PRIMARY KEY,
	item_condition_id VARCHAR(32) NOT NULL,
	brand_name VARCHAR(32) NOT NULL DEFAULT 'None',
	price DECIMAL(10,2) NOT NULL,
	main_category VARCHAR(32) UNIQUE NOT NULL,
	Date_Posted DATE NOT NULL,
	Seller VARCHAR(64) NOT NULL REFERENCES Seller(Seller) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Purchased CHAR(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Transactions (
	transactionid CHAR(14) PRIMARY KEY,
	Buyer VARCHAR(16) NOT NULL REFERENCES Buyer(Buyer) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Seller VARCHAR(16) NOT NULL REFERENCES Seller(Seller) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Listing VARCHAR(16) NOT NULL REFERENCES Listings(Name) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	transactiondate TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Categories (
	Category CHAR(16) NOT NULL REFERENCES Listings(main_category) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Description VARCHAR(64) NOT NULL,
	PRIMARY KEY (Category)
);

CREATE TABLE IF NOT EXISTS Admins (
	Email VARCHAR(256) PRIMARY KEY,
	Username CHAR(14) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Join_date DATE NOT NULL
);