CREATE TABLE IF NOT EXISTS Users (
	Email VARCHAR(256) NOT NULL,
	Username VARCHAR(64) UNIQUE NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Join_date DATE NOT NULL,
	PRIMARY KEY(Email)
);

CREATE TABLE IF NOT EXISTS Seller (
	Seller VARCHAR(64) NOT NULL REFERENCES Users(Username) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Email VARCHAR(256) NOT NULL,
	Number VARCHAR(20) UNIQUE NOT NULL,
	PRIMARY KEY (Seller),
	FOREIGN KEY (Email) REFERENCES Users(Email) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS Buyer (
	Buyer VARCHAR(64) REFERENCES Users(Username) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Email VARCHAR(256) NOT NULL,
	Number VARCHAR(20) UNIQUE NOT NULL,
	PRIMARY KEY(Buyer),
	FOREIGN KEY (Email) REFERENCES Users(Email) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS Listings (
	Listingid VARCHAR(16) PRIMARY KEY,
	Name VARCHAR(256) NOT NULL,
	item_condition_id VARCHAR(32) NOT NULL,
	brand_name VARCHAR(32) NOT NULL DEFAULT 'None',
	price DECIMAL(10,2) NOT NULL,
	main_category VARCHAR(32) NOT NULL,
	Date_Posted DATE NOT NULL,
	Seller VARCHAR(256) NOT NULL REFERENCES Seller(Seller) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Purchased VARCHAR(5) DEFAULT 'false'
);

CREATE TABLE IF NOT EXISTS Transactions (
	transactionid CHAR(14) PRIMARY KEY,
	Buyer VARCHAR(256) NOT NULL REFERENCES Buyer(Buyer) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Seller VARCHAR(256) NOT NULL REFERENCES Seller(Seller) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	Listing VARCHAR(256) NOT NULL REFERENCES Listings(Listingid) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	transactiondate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Categories (
	Category VARCHAR(32) NOT NULL,
	Description VARCHAR(256) NOT NULL,
	PRIMARY KEY (Category)
);

CREATE TABLE IF NOT EXISTS Admins (
	Email VARCHAR(256) PRIMARY KEY,
	Username CHAR(64) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Join_date DATE NOT NULL
);