version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Listify2023
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7890:8080
